# Homebrew formula for fontina.
#
# Generated by scripts/package-manifests; edit that, not this.
# The release workflow copies it into the tap at oddurs/homebrew-fontina,
# which is what `brew tap oddurs/fontina && brew install fontina` reads.
#
# A binary formula, not a source one: the release already builds and attests four platform
# archives, and asking every installer to compile the workspace again would spend minutes
# arriving at the same bytes.
class Fontina < Formula
  desc "Lightweight, cross-platform font manager for the terminal"
  homepage "https://github.com/oddurs/fontina"
  version "0.1.1"
  license "GPL-3.0-or-later"

  on_macos do
    on_arm do
      url "https://github.com/oddurs/fontina/releases/download/v0.1.1/fontina-v0.1.1-aarch64-apple-darwin.tar.gz"
      sha256 "4269b1999329d3ce015c5f59db8e670791d52059c7779e5d2ba648afe65bd6f3"
    end
    on_intel do
      url "https://github.com/oddurs/fontina/releases/download/v0.1.1/fontina-v0.1.1-x86_64-apple-darwin.tar.gz"
      sha256 "d1de743128f1a1104dfdce1fda522079b05db777c2f333a9e30c01881aa44edf"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/oddurs/fontina/releases/download/v0.1.1/fontina-v0.1.1-aarch64-unknown-linux-musl.tar.gz"
      sha256 "4852fd307a651f1857bff2ec6639c5b789434f46d5da5f1bdf03e567a08e6517"
    end
    on_intel do
      url "https://github.com/oddurs/fontina/releases/download/v0.1.1/fontina-v0.1.1-x86_64-unknown-linux-musl.tar.gz"
      sha256 "2d3e3f1fdccd0e06fdb1fe535e29f707516443786e602ca2d852ae54e5c7a297"
    end
  end

  def install
    bin.install "fontina"
    man1.install Dir["man/*.1"]
    bash_completion.install "completions/fontina.bash" => "fontina"
    zsh_completion.install "completions/_fontina"
    fish_completion.install "completions/fontina.fish"
    doc.install "README.md", "COPYING", "fontina.texi"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fontina --version")

    # The index is fontina's only state and it lives where the OS says it should, so the
    # test points it somewhere disposable rather than writing to the tester's own.
    ENV["FONTINA_DB"] = testpath/"index.db"

    # A schema is the cheapest proof the binary is whole: it exercises the metadata model
    # and its serialisation without needing a font on disk.
    assert_match "FaceMetadata", shell_output("#{bin}/fontina schema face")

    # An empty index answers rather than failing, which is what a first run depends on.
    assert_match "no faces", shell_output("#{bin}/fontina list")
  end
end
